### ISSUE TITLE
Booked Office still shows available.

### ISSUE THREAD

**Issue by AnkitSharmaOnGithub** [AbijahKaj/officina#11]
When i book an office for a particular date. And after that i visit the page again it still shows available. 
![1](https://user-images.githubusercontent.com/53289186/89739462-7cb2c500-da9e-11ea-9feb-b7a8a52a9628.png)

**Comment by Tamarpe** [comment]
It's OK - when you book it on a specific date, then someone can book it on another date..

The problem is that indeed people can book an office on overlapping dates - but this is not a problem, as the owner of the office should approve/reject the orders he gets, so he just can reject when he sees another order with overlapping dates

**Comment by AnkitSharmaOnGithub** [comment]
Ok. I got the point. Basically, we have MCQ's for the owner of the office. Closing the issue.
